### PR TITLE
Remove user metrics code that isn't being used anymore for a nice performance boost

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
@ag_dubs r?

**Comment by jbuck** [comment]
@ashleygwilliams r?

**Comment by ashleygwilliams** [comment]
r+ 

way to go this is aweeeeeesooommeeeee woo

**Comment by jbuck** [comment]
@adamlofting Also, can we chat tomorrow about the impact of removing this code? It's such a big performance win I think we need to do it, but I'd like to help you replace any sources of metrics data you're losing.

**Pull request merged**
