### PR TITLE
Replace bcrypt library with bcrypt.js, Closes #386

### LINKED ISSUE #386: Migrate away from native bcrypt with Javascript bindings
We currently use a native version of bcrypt with Javascript bindings as our library of choice. This is problematic because this library lacks pre-built binaries, which forces ```node-gyp``` to fallback to manual compilation of the library. This causes issues when setting up login, especially if you don't have your environment setup right.

Let's switch over to something like: https://www.npmjs.com/package/bcryptjs, it's slower but it's written in Javascript entirely and removes the requirement to manually compile bcrypt.

### PR DESCRIPTION
**Pull request by ryanwarsaw**
I reviewed the method structure for our current usage of bcrypt and cross-checked it with the method structures for bcrypt.js and it's basically a drop and replace solution. If someone could review this and ensure everything is functioning properly, that'd be great.

I'm filing a separate PR to remove the redundant New Relic references, I wanted to keep this PR as simple as possible and only include the changes relevant for it to function properly.

### CODE REVIEW

**Comment by ryanwarsaw** [comment]
Don't merge this, it looks like something is still going on with Travis CI but it isn't failing the build.

**Comment by ryanwarsaw** [comment]
@cadecairos What are your thoughts on merging this? I've looked into this further and the effects of this change are nullified by the fact that other dependencies within this project (sqlite3) and others in the Thimble chain would still require on-site compilation with gcc/clang if a remote binary isn't present.

That and the fact that this will ultimately make things slower and less performant for better or worse, I'm having a hard time justifying this change but want to leave it to you for final opinions.

**Comment by Pomax** [comment]
repinging @cadecairos to make sure this isn't lost - it's currently blocking some dependency upgrade work in Thimble.

**Comment by humphd** [comment]
@ryanwarsaw can I get an update from you on this?  I'd like to move the LTS stuff in thimble forward.  Thanks.

**Comment by ryanwarsaw** [comment]
@humphd Yeah, i'm just going to go cold turkey on this one 🤞

**Pull request merged**
