### PR TITLE
Login 3 Testing

### PR DESCRIPTION
**Pull request by cadecairos**
Implement straight-forward API testing for login with mocha, supertest and assert

### CODE REVIEW

**Comment by jbuck** [comment]
This code looks fine, but the CI is failing

**Comment by Pomax** [comment]
yeah, works great locally, but we probably want to figure out what's tripping up Travis before this can land.

**Comment by cadecairos** [comment]
Tests passing now (removed unneeded travis env settings)

 R? @jbuck

**Comment by jbuck** [comment]
@cadecairos r+

**Pull request merged**
