### PR TITLE
Node update

### PR DESCRIPTION
**Pull request by gideonthomas**
Will update description when i get a sec. One major change I made was I removed js beautifier because it was breaking everything. I thought we don't really need it but let me know if we do.

### CODE REVIEW

**Comment by gideonthomas** [comment]
ugh, I'll fix the travis errors

**Comment by cadecairos** [comment]
@gideonthomas *poke*

**Comment by gideonthomas** [comment]
@cadecairos sorry, I'll try to get to this sometime this week. Until then would you be able to take one final look at the id patch: https://github.com/mozilla/id.webmaker.org/pull/447

**Comment by cadecairos** [comment]
got any time to invest on this in the next little while @gideonthomas?

**Comment by gideonthomas** [comment]
yeah, the creator patch for pulse was the biggest issue that needed to be fixed. I have one small follow-up to do and then I can revisit this.

**Review by cadecairos — APPROVED** [review]
This seems to work just fine locally, lets get it on staging and kick the tires.

**Pull request merged**
