### PR TITLE
Update bcrypt to v0.8.2

### PR DESCRIPTION
**Pull request by alicoding**
@jbuck R?

### CODE REVIEW

**Comment by alicoding** [comment]
Apparently this module doesn't work with newer version of node, so upgrading this to `0.8.2` fixes the issue and now we can run with node `0.12.0+`

**Comment by jbuck** [comment]
@alicoding r+ when travis goes green

**Comment by alicoding** [comment]
The error was:

```
☁  login.webmaker.org [master] node app
/Users/ali/projects/webmaker-suite/login.webmaker.org/node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/ali/projects/webmaker-suite/login.webmaker.org/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/Users/ali/projects/webmaker-suite/login.webmaker.org/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by ashleygwilliams** [comment]
related: #357

**Comment by ashleygwilliams** [comment]
closing this PR in favor of one that will take care of all dep updates for 0.12.

**Pull request closed without merging**
